### ISSUE TITLE
[12+] maintenance_equipment_always_fold: add dependencies

### ISSUE THREAD

**Issue by mymage** [OCA/maintenance#156]
Just for who as me that can have some doubts, I think it is better to add dependencies from maintenance_equipment_category_kanban to this module, otherwise it hasn't effect right? Until you don't create your own kanban view.

**Comment by dalonsod** [comment]
Hello @mymage , thanks for your contribution.

I think you're right, `maintenance_equipment_always_fold` should depend on `maintenance_equipment_category_kanban`. `maintenance_equipment_category_kanban` was added after, and we didn't notice that proper dependency. In fact, these two addons could be merged in a single one.

@etobella what you you think?
- For v14 we should consider merging addons, since they're not migrated yet
- For v12 and v13, the best solution should be simply adding the missing dependency?
Thanks!
