### ISSUE TITLE
Cron job doesn't work on Odoo 12

### ISSUE THREAD

**Issue by quachngocxuan** [OCA/maintenance#46]
Hi team,

The module documentation states that a cron job is used to create maintenance request from the maintenance plan. I've tried to create a maintenance plan but no maintenance request was created. So I saw the source code, and found out that the cron job here is a method and it isn't called anywhere.

To solve the problem, I've tried to add some code snippet to call the cron job method when creating an equipment like this:

```
@api.model
    def create(self, vals):
        new_equipment = super(MaintenanceEquipment, self).create(vals)

        self._cron_generate_requests()
        
        return new_equipment
```

Is it a bug or I did something wrong so it didn't work fine?

Thank you.

**Comment by dalonsod** [comment]
Hello,

the defined cron in `maintenance` addon fires the `_cron_generate_requests()` method of `maintenance.equipment` model. `maintenance_plan` addon overrides that method (https://github.com/OCA/maintenance/blob/12.0/maintenance_plan/models/maintenance.py#L173) in order to change the request generation using the plans instead.

So the original cron (called "Maintenance: generate preventive maintenance requests") is the only one. Then, you should fire it manually and check if there is any error during its execution.

**Comment by etobella** [comment]
The requests will be created as soon as the cron is executed, you need to wait, or, as @dalonsod said execute it manually (you can find it on debug mode, `Settings > Technical > Automation > Scheduled actions`
